version 13

diff --git a/update-version b/update-version
--- a/update-version
+++ b/update-version
@@ -11,8 +11,8 @@ die() {
 }
 
 # regular expressions
-UV_REGEX_VERSION_TAG="^INS_VERSION=[0-9]{1,20}$";
-UV_REGEX_VERSION="[0-9]{1,20}$";
+UV_REGEX_VERSION_TAG="^INS_VERSION=[0-9]{1,20}$"
+UV_REGEX_VERSION="[0-9]{1,20}$"
 
 # receive script
 UV_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
@@ -24,23 +24,29 @@ UV_SCRIPT="${UV_SCRIPT_DIR}/${UV_SCRIPT_NAME}"
 
 # receive current version
 UV_CURRENT_TAG=$(grep -E "${UV_REGEX_VERSION_TAG}" "${UV_SCRIPT}")
-log "current tag: ${UV_CURRENT_TAG}"
+UV_TAGS_RESULTS_COUNT=$(echo "${UV_CURRENT_TAG}" | wc -l | xargs echo -n)
+[[ "${UV_TAGS_RESULTS_COUNT}" == "1" ]] || die "ERROR: found more than one (${UV_TAGS_RESULTS_COUNT}) version tag."
 [[ "${UV_CURRENT_TAG}" == "" ]] && die "ERROR: can't receive version tag."
-echo "${UV_CURRENT_TAG}" | wc
 
 UV_CURRENT_VERSION=$(echo "${UV_CURRENT_TAG}" | grep -o -E "${UV_REGEX_VERSION}")
-log "current version: ${UV_CURRENT_VERSION}"
 [[ "${UV_CURRENT_VERSION}" == "" ]] && die "ERROR: can't receive version."
 
 # calculate next version
-UV_NEW_VERSION=$((UV_CURRENT_VERSION+1))
+UV_NEW_VERSION=$((UV_CURRENT_VERSION + 1))
 UV_NEW_TAG="INS_VERSION=${UV_NEW_VERSION}"
 
+# dry sed run
+UV_CHANGES=$(sed -n "s/${UV_CURRENT_TAG}/${UV_NEW_TAG}/gp" "${UV_SCRIPT}")
+[[ "${UV_NEW_TAG}" == "${UV_CHANGES}" ]] || die "ERROR: changes not as expected. expected: '${UV_NEW_TAG}' after change: '${UV_CHANGES}'"
 
-log "new version: ${UV_NEW_VERSION}"
-log "new tag: ${UV_NEW_TAG}"
+# wet sed run
+sed -i "" "s/${UV_CURRENT_TAG}/${UV_NEW_TAG}/g" "${UV_SCRIPT}"
 
-sed -n "s/${UV_CURRENT_TAG}/${UV_NEW_TAG}/gp" "${UV_SCRIPT}"
+log "upgrade from ${UV_CURRENT_VERSION} to ${UV_NEW_VERSION}"
+
+git add .
+git commit -m "version ${UV_NEW_VERSION}"
+git push
 
 # print empty line on end
 echo ""
